[package]
name = "common"
version = "0.1.0"
authors = ["Bryan Chen <bryanchen74@gmail.com>"]
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8.4"

[dev-dependencies]
termion = "1.5"
criterion = { version = "0.3", features = ["html_reports"] }

[profile.release]
debug = true

[[bench]]
name = "my_bench"
harness = false
